// src/constants/nflTeams.ts
export const NFL_TEAMS: { [key: string]: string[] } = {
  'Arizona Cardinals': ['ARI', 'Cardinals', 'Arizona'],
  'Atlanta Falcons': ['ATL', 'Falcons', 'Atlanta'],
  'Baltimore Ravens': ['BAL', 'Ravens', 'Baltimore'],
  'Buffalo Bills': ['BUF', 'Bills', 'Buffalo'],
  'Carolina Panthers': ['CAR', 'Panthers', 'Carolina'],
  'Chicago Bears': ['CHI', 'Bears', 'Chicago'],
  'Cincinnati Bengals': ['CIN', 'Bengals', 'Cincinnati'],
  'Cleveland Browns': ['CLE', 'Browns', 'Cleveland'],
  'Dallas Cowboys': ['DAL', 'Cowboys', 'Dallas'],
  'Denver Broncos': ['DEN', 'Broncos', 'Denver'],
  'Detroit Lions': ['DET', 'Lions', 'Detroit'],
  'Green Bay Packers': ['GB', 'Packers', 'Green Bay'],
  'Houston Texans': ['HOU', 'Texans', 'Houston'],
  'Indianapolis Colts': ['IND', 'Colts', 'Indianapolis'],
  'Jacksonville Jaguars': ['JAX', 'Jaguars', 'Jacksonville'],
  'Kansas City Chiefs': ['KC', 'Chiefs', 'Kansas City'],
  'Las Vegas Raiders': ['LV', 'Raiders', 'Las Vegas', 'Vegas'],
  'Los Angeles Chargers': ['LAC', 'Chargers', 'LA Chargers', 'L.A. Chargers'],
  'Los Angeles Rams': ['LAR', 'Rams', 'LA Rams', 'L.A. Rams'],
  'Miami Dolphins': ['MIA', 'Dolphins', 'Miami'],
  'Minnesota Vikings': ['MIN', 'Vikings', 'Minnesota'],
  'New England Patriots': ['NE', 'Patriots', 'New England', 'Pats'],
  'New Orleans Saints': ['NO', 'Saints', 'New Orleans'],
  'New York Giants': ['NYG', 'Giants', 'NY Giants', 'N.Y. Giants'],
  'New York Jets': ['NYJ', 'Jets', 'NY Jets', 'N.Y. Jets'],
  'Philadelphia Eagles': ['PHI', 'Eagles', 'Philadelphia', 'Philly'],
  'Pittsburgh Steelers': ['PIT', 'Steelers', 'Pittsburgh'],
  'San Francisco 49ers': ['SF', '49ers', 'San Francisco', 'Niners', 'San Fran'],
  'Seattle Seahawks': ['SEA', 'Seahawks', 'Seattle'],
  'Tampa Bay Buccaneers': ['TB', 'Buccaneers', 'Tampa Bay', 'Tampa', 'Bucs'],
  'Tennessee Titans': ['TEN', 'Titans', 'Tennessee'],
  'Washington Commanders': ['WAS', 'Commanders', 'Washington', 'Washington Football'],
};